apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wnig53lm3-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wnig53lm3-java-quarkus-gitops